// Complete list of Ford dealerships within ~150 miles of Midland TX (79701)
// Each entry has the inventory search URL pre-filtered to new Raptor/Raptor R
// Platform types:
//   'dealerdotcom' - standard /new-inventory/?model=F-150&trim=Raptor URL
//   'vinsolutions'  - VinSolutions platform
//   'custom'        - dealer-specific URL

export const DEALERS = [
  // ── CORE PERMIAN BASIN ──────────────────────────────────
  {
    name:     'Sewell Ford',
    city:     'Odessa',
    state:    'TX',
    miles:    20,
    url:      'https://www.sewellford.com',
    // Sewell uses a standard dealer.com / CDK platform with filterable inventory
    inventoryUrl: 'https://www.sewellford.com/new-vehicles/?model=F-150&trim=Raptor&trim=Raptor+R',
    platform: 'dealerdotcom',
  },
  {
    name:     'Rogers Ford',
    city:     'Midland',
    state:    'TX',
    miles:    0,
    url:      'https://www.rogersford.com',
    inventoryUrl: 'https://www.rogersford.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Bailey Toliver Ford',
    city:     'Stanton',
    state:    'TX',
    miles:    35,
    url:      'https://www.baileytoliverford.com',
    inventoryUrl: 'https://www.baileytoliverford.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'AutoInc Ford (Odessa)',
    city:     'Odessa',
    state:    'TX',
    miles:    20,
    url:      'https://www.autoinc.com',
    inventoryUrl: 'https://www.autoinc.com/new-inventory/?location=odessa&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'AutoInc Ford (Midland)',
    city:     'Midland',
    state:    'TX',
    miles:    0,
    url:      'https://www.autoinc.com',
    inventoryUrl: 'https://www.autoinc.com/new-inventory/?location=midland&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  // ── NEAR PERMIAN ────────────────────────────────────────
  {
    name:     'Star Ford',
    city:     'Big Spring',
    state:    'TX',
    miles:    40,
    url:      'https://www.starfordbigspring.com',
    inventoryUrl: 'https://www.starfordbigspring.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Permian Ford (Andrews)',
    city:     'Andrews',
    state:    'TX',
    miles:    36,
    url:      'https://www.permianford.net',
    inventoryUrl: 'https://www.permianford.net/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Premier Ford of Lamesa',
    city:     'Lamesa',
    state:    'TX',
    miles:    51,
    url:      'https://www.premierfordoflamesa.com',
    inventoryUrl: 'https://www.premierfordoflamesa.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Smith Auto Family Ford',
    city:     'Levelland',
    state:    'TX',
    miles:    75,
    url:      'https://www.smithautofamily.com',
    inventoryUrl: 'https://www.smithautofamily.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Permian Ford (Hobbs NM)',
    city:     'Hobbs',
    state:    'NM',
    miles:    78,
    url:      'https://www.permianford.net',
    inventoryUrl: 'https://www.permianford.net/new-inventory/index.htm?location=hobbs&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'Stanley Ford Sweetwater',
    city:     'Sweetwater',
    state:    'TX',
    miles:    90,
    url:      'https://www.stanleyfordsweetwater.com',
    inventoryUrl: 'https://www.stanleyfordsweetwater.com/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  // ── OUTER RANGE ─────────────────────────────────────────
  {
    name:     'Arrow Ford',
    city:     'Abilene',
    state:    'TX',
    miles:    101,
    url:      'https://www.arrowford.net',
    inventoryUrl: 'https://www.arrowford.net/new-inventory/index.htm?model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'AutoInc Ford (Abilene)',
    city:     'Abilene',
    state:    'TX',
    miles:    101,
    url:      'https://www.autoinc.com',
    inventoryUrl: 'https://www.autoinc.com/new-inventory/?location=abilene&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'AutoInc Ford (San Angelo)',
    city:     'San Angelo',
    state:    'TX',
    miles:    101,
    url:      'https://www.autoinc.com',
    inventoryUrl: 'https://www.autoinc.com/new-inventory/?location=sanangelo&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
  {
    name:     'AutoInc Ford (Lubbock)',
    city:     'Lubbock',
    state:    'TX',
    miles:    115,
    url:      'https://www.autoinc.com',
    inventoryUrl: 'https://www.autoinc.com/new-inventory/?location=lubbock&model=F-150&trim=Raptor',
    platform: 'dealerdotcom',
  },
];
